### ISSUE TITLE
Leaving year out of Options breaks URL and urldate

### ISSUE THREAD

**Issue by El-Cerdo** [JonasMoennig/currentPageToBibTeX#1]
I have tried to use these options:

```
@online{cite_key,
    author = {$author$},
    title = {{$title$}},
    url = {$url$},
    lastchecked = {$urldate$}
}
```

URL and lastchecked don't appear, unless I add the $time$ tag anywhere.

**Comment by JonasMoennig** [comment]
Sorry, that i got to this so late. Somehow I did not get an email notification for this issue. The bug is fixed now. The updated version is now awaiting approval and should be live on the Mozilla AddOn store in a couple of days.
