### ISSUE TITLE
Show only unique alternative suggestions

### ISSUE THREAD

**Issue by exploide** [JonasMoennig/currentPageToBibTeX#4]
The pop-up that allows to choose alternative values for keys like `author` should only contain unique suggestions. E.g. see the `author` suggestions for this repo's page. It shows 'JonasMoennig' four times.

Additionally, when there are no alternative suggestions, don't show this pop-up at all.

**Comment by JonasMoennig** [comment]
I just fixed this. I will upload a new version to the add-on store this evening. I might close some other issues as well before this.
